#!/usr/bin/env python3
"""
backfill_history.py
-------------------
Backfills historical probability data from Polymarket's CLOB price-history
API into docs/data.json.

Reads token IDs from markets_config.json (generated by auto_discover.py).
Skips markets that already have ≥ MIN_EXISTING_PTS data points.
Only backfills markets that are new or have sparse history.

Called automatically by GitHub Actions after auto_discover.py runs.

Usage:
    python3 backfill_history.py               # default: 365 days, skip if ≥100 pts
    python3 backfill_history.py --days 180    # 180 days back
    python3 backfill_history.py --force       # re-backfill all, even existing
    python3 backfill_history.py --min-pts 50  # skip threshold (default 100)
"""

import json
import subprocess
import os
import sys
import time
from datetime import datetime, timezone

CLOB_API       = "https://clob.polymarket.com/prices-history"
CONFIG_PATH    = os.path.join(os.path.dirname(__file__), "markets_config.json")
DATA_PATH      = os.path.join(os.path.dirname(__file__), "docs", "data.json")
DOWNSAMPLE_MIN = 30      # keep one point per 30-minute bucket
MAX_HISTORY    = 17520   # ~1 year at 30-min intervals


def parse_args():
    days     = 365
    force    = "--force" in sys.argv
    min_pts  = 100
    if "--days" in sys.argv:
        try: days = int(sys.argv[sys.argv.index("--days") + 1])
        except (IndexError, ValueError): pass
    if "--min-pts" in sys.argv:
        try: min_pts = int(sys.argv[sys.argv.index("--min-pts") + 1])
        except (IndexError, ValueError): pass
    return days, force, min_pts


def fetch_clob(token_id: str, start_ts: int) -> list:
    url = f"{CLOB_API}?market={token_id}&startTs={start_ts}&fidelity=60"
    result = subprocess.run(
        ["curl", "-s", "--max-time", "20", "-H", "User-Agent: Mozilla/5.0", url],
        capture_output=True, text=True, timeout=25
    )
    try:
        return json.loads(result.stdout).get("history", [])
    except Exception:
        return []


def downsample(points: list, interval_min: int = 30) -> list:
    if not points:
        return []
    iv = interval_min * 60
    buckets = {}
    for p in points:
        bucket = (p["t"] // iv) * iv
        buckets[bucket] = p["p"]
    return [
        {"t": datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
         "v": round(price, 4)}
        for ts, price in sorted(buckets.items())
    ]


def merge(existing: list, backfilled: list) -> list:
    seen = {h["t"] for h in existing}
    merged = [h for h in backfilled if h["t"] not in seen]
    merged.extend(existing)
    merged.sort(key=lambda h: h["t"])
    return merged[-MAX_HISTORY:]


def load_config() -> list:
    if not os.path.exists(CONFIG_PATH):
        print(f"ERROR: {CONFIG_PATH} not found. Run auto_discover.py first.")
        sys.exit(1)
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)
    return cfg.get("markets", [])


def load_data() -> dict:
    if os.path.exists(DATA_PATH):
        try:
            with open(DATA_PATH) as f:
                return json.load(f)
        except Exception:
            pass
    return {"last_updated": None, "categories": {}, "markets": {}}


def main():
    days, force, min_pts = parse_args()
    start_ts = int(time.time()) - days * 86400

    print(f"Backfill: {days}d window | skip if ≥{min_pts} pts | force={force}")

    cfg_markets = load_config()
    data        = load_data()

    # Build token map from config
    token_map = {}
    for m in cfg_markets:
        mid      = m.get("id")
        token_id = m.get("clob_token_id")
        if mid and token_id:
            token_map[mid] = token_id

    if not token_map:
        print("No clob_token_ids found in markets_config.json — nothing to backfill.")
        return

    updated = skipped = errors = 0

    for mid, token_id in token_map.items():
        existing = data.get("markets", {}).get(mid, {}).get("history", [])
        n_pts    = len(existing)

        if not force and n_pts >= min_pts:
            skipped += 1
            continue   # already has plenty of history

        print(f"  [{mid}] existing={n_pts} pts...", end=" ", flush=True)

        raw = fetch_clob(token_id, start_ts)
        if not raw:
            print("⚠ no data")
            errors += 1
            continue

        downsampled = downsample(raw, DOWNSAMPLE_MIN)
        merged      = merge(existing, downsampled)

        if mid not in data.setdefault("markets", {}):
            data["markets"][mid] = {}
        data["markets"][mid]["history"] = merged

        gain = len(merged) - n_pts
        print(f"✓ {len(raw)} raw → {len(downsampled)} pts → merged={len(merged)} (+{gain})")
        updated += 1
        time.sleep(0.05)

    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=True)
    with open(DATA_PATH, "w") as f:
        json.dump(data, f, separators=(",", ":"))

    print(f"\n✅ Done: {updated} backfilled, {skipped} skipped (already rich), {errors} errors")


if __name__ == "__main__":
    main()
