#!/usr/bin/env python3
"""
backfill_history.py
-------------------
Backfills historical probability data from Polymarket's CLOB price-history
API into docs/data.json.

Reads token IDs from markets_config.json (generated by auto_discover.py).
Skips markets that already have ≥ MIN_EXISTING_PTS data points.
Only backfills markets that are new or have sparse history.

Called automatically by GitHub Actions after auto_discover.py runs.

Usage:
    python3 backfill_history.py               # default: 365 days, skip if ≥100 pts
    python3 backfill_history.py --days 180    # 180 days back
    python3 backfill_history.py --force       # re-backfill all, even existing
    python3 backfill_history.py --min-pts 50  # skip threshold (default 100)
"""

import json
import subprocess
import os
import sys
import time
from datetime import datetime, timezone

CLOB_API       = "https://clob.polymarket.com/prices-history"
CONFIG_PATH    = os.path.join(os.path.dirname(__file__), "markets_config.json")
DATA_PATH      = os.path.join(os.path.dirname(__file__), "docs", "data.json")
DOWNSAMPLE_MIN = 30      # keep one point per 30-min bucket (for recent data)
MAX_HISTORY    = 17520   # ~1 year at 30-min intervals

# Use daily fidelity for data older than 30 days (matches Polymarket chart style,
# avoids thin-liquidity hourly spikes). Use hourly for recent 30 days.
DAILY_CUTOFF_DAYS = 30   # days back from today where we switch from hourly → daily


def parse_args():
    days     = 365
    force    = "--force" in sys.argv
    min_pts  = 100
    if "--days" in sys.argv:
        try: days = int(sys.argv[sys.argv.index("--days") + 1])
        except (IndexError, ValueError): pass
    if "--min-pts" in sys.argv:
        try: min_pts = int(sys.argv[sys.argv.index("--min-pts") + 1])
        except (IndexError, ValueError): pass
    return days, force, min_pts


def fetch_clob(token_id: str, start_ts: int) -> list:
    """
    Fetch CLOB price history using two passes:
    1. Full range with daily fidelity (fidelity=1440) — smooth, no thin-liquidity spikes
    2. Recent 30 days with hourly fidelity (fidelity=60) — precise recent data

    The two sets are merged: recent hourly overrides daily for the overlap period.
    This matches Polymarket's own chart display (they show daily for history).
    """
    now = int(time.time())

    # Pass 1: Full history at daily granularity
    url_daily = f"{CLOB_API}?market={token_id}&startTs={start_ts}&fidelity=1440"
    result = subprocess.run(
        ["curl", "-s", "--max-time", "20", "-H", "User-Agent: Mozilla/5.0", url_daily],
        capture_output=True, text=True, timeout=25
    )
    daily_pts = []
    try:
        daily_pts = json.loads(result.stdout).get("history", [])
    except Exception:
        pass

    # Pass 2: Recent 30 days at hourly granularity
    recent_start = now - DAILY_CUTOFF_DAYS * 86400
    url_hourly = f"{CLOB_API}?market={token_id}&startTs={recent_start}&fidelity=60"
    result2 = subprocess.run(
        ["curl", "-s", "--max-time", "20", "-H", "User-Agent: Mozilla/5.0", url_hourly],
        capture_output=True, text=True, timeout=25
    )
    hourly_pts = []
    try:
        hourly_pts = json.loads(result2.stdout).get("history", [])
    except Exception:
        pass

    # Merge: use daily for old data, hourly for recent (hourly takes precedence)
    cutoff_t = recent_start
    combined = [p for p in daily_pts if p["t"] < cutoff_t] + hourly_pts

    return combined


def downsample(points: list, interval_min: int = 30) -> list:
    """Downsample raw CLOB history to fixed intervals.
    For daily points (fidelity=1440), keeps each daily point as-is.
    For hourly points, downsamples to 30-min buckets.
    """
    if not points:
        return []
    iv = interval_min * 60
    buckets = {}
    for p in points:
        bucket = (p["t"] // iv) * iv
        buckets[bucket] = p["p"]   # last-write-wins within bucket
    return [
        {"t": datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
         "v": round(price, 4)}
        for ts, price in sorted(buckets.items())
    ]


def merge(existing: list, backfilled: list) -> list:
    seen = {h["t"] for h in existing}
    merged = [h for h in backfilled if h["t"] not in seen]
    merged.extend(existing)
    merged.sort(key=lambda h: h["t"])
    return merged[-MAX_HISTORY:]


def load_config() -> list:
    if not os.path.exists(CONFIG_PATH):
        print(f"ERROR: {CONFIG_PATH} not found. Run auto_discover.py first.")
        sys.exit(1)
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)
    return cfg.get("markets", [])


def load_data() -> dict:
    if os.path.exists(DATA_PATH):
        try:
            with open(DATA_PATH) as f:
                return json.load(f)
        except Exception:
            pass
    return {"last_updated": None, "categories": {}, "markets": {}}


def remove_spikes(history: list, max_jump: float = 0.25) -> list:
    """
    Remove isolated price spikes from history.
    A spike is a point where:
    - The price changes by > max_jump from the previous point AND
    - The price reverts > max_jump within the next 1-3 points
    These are thin-liquidity artifacts, not genuine market moves.
    """
    if len(history) < 4:
        return history
    cleaned = [history[0]]
    i = 1
    while i < len(history):
        prev = cleaned[-1]['v']
        curr = history[i]['v']
        jump = abs(curr - prev)

        # Check if this is a spike (big jump followed by reversal)
        if jump > max_jump and i + 1 < len(history):
            # Look ahead 1-3 points for reversal
            spike = True
            for look in range(1, min(4, len(history) - i)):
                next_v = history[i + look]['v']
                # If next point is close to prev (not curr), it's a spike
                if abs(next_v - prev) < jump * 0.6:
                    spike = True
                    break
                if abs(next_v - curr) < jump * 0.4:
                    spike = False  # sustained move, not a spike
                    break

            if spike:
                i += 1  # skip the spike point
                continue

        cleaned.append(history[i])
        i += 1
    return cleaned


def main():
    days, force, min_pts = parse_args()
    start_ts = int(time.time()) - days * 86400

    print(f"Backfill: {days}d window | skip if ≥{min_pts} pts | force={force}")
    print(f"  Old data (>{DAILY_CUTOFF_DAYS}d): daily fidelity (no spikes)")
    print(f"  Recent data (≤{DAILY_CUTOFF_DAYS}d): hourly fidelity")

    cfg_markets = load_config()
    data        = load_data()

    # Build token map from config
    token_map = {}
    for m in cfg_markets:
        mid      = m.get("id")
        token_id = m.get("clob_token_id")
        if mid and token_id:
            token_map[mid] = token_id

    if not token_map:
        print("No clob_token_ids found in markets_config.json — nothing to backfill.")
        return

    updated = skipped = errors = 0

    for mid, token_id in token_map.items():
        existing = data.get("markets", {}).get(mid, {}).get("history", [])
        n_pts    = len(existing)

        if not force and n_pts >= min_pts:
            skipped += 1
            continue   # already has plenty of history

        print(f"  [{mid}] existing={n_pts} pts...", end=" ", flush=True)

        raw = fetch_clob(token_id, start_ts)
        if not raw:
            print("⚠ no data")
            errors += 1
            continue

        downsampled = downsample(raw, DOWNSAMPLE_MIN)
        cleaned     = remove_spikes(downsampled)
        merged      = merge(existing, cleaned)

        if mid not in data.setdefault("markets", {}):
            data["markets"][mid] = {}
        data["markets"][mid]["history"] = merged

        gain = len(merged) - n_pts
        removed = len(downsampled) - len(cleaned)
        spike_note = f" (removed {removed} spikes)" if removed else ""
        print(f"✓ {len(raw)} raw → {len(downsampled)} pts → {len(cleaned)} clean{spike_note} → merged={len(merged)} (+{gain})")
        updated += 1
        time.sleep(0.05)

    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=True)
    with open(DATA_PATH, "w") as f:
        json.dump(data, f, separators=(",", ":"))

    print(f"\n✅ Done: {updated} backfilled, {skipped} skipped (already rich), {errors} errors")


if __name__ == "__main__":
    main()
